title: "General Surgery Residency Handbook"
description: "A comprehensive handbook for General Surgery residents."
theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-include-cache
